//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_AEA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampagneClient
    {
        public long CampagneClientID { get; set; }
        public long CampagneID { get; set; }
        public long ClientID { get; set; }
    
        public virtual Campagne Campagne { get; set; }
        public virtual Client Client { get; set; }
    }
}
