//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_AEA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dossier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dossier()
        {
            this.Voyageurs = new HashSet<Voyageur>();
        }
    
        public long DossierID { get; set; }
        public int NbVoyageurDossier { get; set; }
        public int NumCB { get; set; }
        public string EmailClient { get; set; }
        public Nullable<long> VoyageID { get; set; }
        public Nullable<long> CarteBancaireID { get; set; }
        public Nullable<long> ClientID { get; set; }
    
        public virtual CarteBancaire CarteBancaire { get; set; }
        public virtual Client Client { get; set; }
        public virtual Voyage Voyage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voyageur> Voyageurs { get; set; }
    }
}
