//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_AEA_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BOVOYAGE_AEAEntities : DbContext
    {
        public BOVOYAGE_AEAEntities()
            : base("name=BOVOYAGE_AEAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campagne> Campagnes { get; set; }
        public virtual DbSet<CampagneClient> CampagneClients { get; set; }
        public virtual DbSet<CarteBancaire> CarteBancaires { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<Dossier> Dossiers { get; set; }
        public virtual DbSet<Pay> Pays { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Voyage> Voyages { get; set; }
        public virtual DbSet<Voyageur> Voyageurs { get; set; }
    
        public virtual ObjectResult<GetListeContinents_Result> GetListeContinents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListeContinents_Result>("GetListeContinents");
        }
    }
}
