//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_AEA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyageur
    {
        public long VoyageurID { get; set; }
        public string NomVoyageur { get; set; }
        public string PrenomVoyageur { get; set; }
        public System.DateTime DateNaissanceVoyageur { get; set; }
        public long DossierID { get; set; }
    
        public virtual Dossier Dossier { get; set; }
    }
}
