//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_AEA_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voyage()
        {
            this.Dossiers = new HashSet<Dossier>();
        }
    
        public long VoyageID { get; set; }
        public string LibelleVoyage { get; set; }
        public string DescriptifVoyage { get; set; }
        public System.DateTime DateDepartVoyage { get; set; }
        public System.DateTime DateRetourVoyage { get; set; }
        public Nullable<long> DisponibiliteVoyage { get; set; }
        public Nullable<double> PrixVoyage { get; set; }
        public long RegionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dossier> Dossiers { get; set; }
        public virtual Region Region { get; set; }
    }
}
